theme: jekyll-theme-minimal
# Jekyll configuration
markdown: kramdown

title                    : "Hyelim Park"
# Site Author
author:
  name             : "Hyelim Park"
  avatar           : "/assets/cat.jpg"
  bio              : "B.S Student"
  location         : "South Korea"
  email            :
  links:
    - label: "hye00525@naver.com"
      icon: "fas fa-fw fa-envelope-square"
     # url: hye00525@naver.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
   #   url: "https://devinlife.com"
